name: Playwright Tests
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        # NOTE: this pins the action to a specific commit sha for security
        # reasons but you can also use a version tag if desired. For example:
        # ianwalter/playwright-container@v3.0.0
        uses: mcr.microsoft.com/playwright:v1.22.0-focal
        with:
          args: npm ci
      - name: Test
        uses: mcr.microsoft.com/playwright:v1.22.0-focal
        with:
          args: npx playwright test
  # test:
  #   timeout-minutes: 60
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-node@v2
  #     with:
  #       node-version: '14.x'
  #   - name: Install dependencies
  #     run: npm ci
  #   - name: Install Playwright Browsers
  #     run: npx playwright install --with-deps
  #   - name: Run Playwright tests
  #     run: npx playwright test
  #   - uses: actions/upload-artifact@v2
  #     if: always()
  #     with:
  #       name: playwright-report
  #       path: playwright-report/
  #       retention-days: 30
  #   - name: Test marketplace action
  #     uses: simple-elf/allure-report-action@master
  #     if: always()
  #     id: allure-report
  #     with:
  #       allure_results: build/allure-results
  #       gh_pages: gh-pages
  #       allure_report: allure-report
  #       allure_history: allure-history
  #   - name: Deploy report to Github Pages
  #     if: always()
  #     uses: peaceiris/actions-gh-pages@v2
  #     env:
  #       PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       PUBLISH_BRANCH: gh-pages
  #       PUBLISH_DIR: allure-history
